Feature branch
SantiagoGuerra/members-only pull request #1
Opened 2019-12-17 22:54 UTC by lhscar56

2019-12-18 01:28 UTC, Ispirett requested changes
## Status Changes required :1st_place_medal: :+1: 
Great Work so far @lhscar56  @SantiagoGuerra :+1:  :+1: 
There just some things to take care of below.


There are some issues to address.

- [x] When trying to save this user there is and error but it' not shown to the user. The data is be rollback back and not saving to the database. The issue seems to be the name validation please show a flash message to the user. you can use  @modelname.errors.full_messages if you wish.
```

Name 
tom

Email 
n@gmail.com

Password 
12345678

Password confirmation 
12345678

```
- [x] The user that posted the post is not showing when a user is logged in. [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/guest_can_see_only_posts_requirement.png)

- [x] [Optional] when on the /signup path it still shows the login form.

2019-12-18 01:28 UTC, Ispirett commented on app/controllers/sessions_controller.rb
> +      cookies.permanent[:remember_token] = user.remember_token
You should be giving the User a new remember token here [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png)
eg:
```
 remember_token = User.generate_remember_token
  user.update_attribute(:remember_token, remember_token)
  cookies.permanent[:remember_token] = remember_token

```

2019-12-18 01:28 UTC, Ispirett commented on app/controllers/sessions_controller.rb
> +  def destroy
This method should set the` @current_user to nil` [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/session_delete_requirement.png)

2019-12-18 01:28 UTC, Ispirett commented on config/routes.rb
> +  get 'posts/new'
You can remove this

2019-12-18 01:28 UTC, Ispirett commented on config/routes.rb
> +  get 'users/index'
this  can also be removed

2019-12-18 23:21 UTC, samgaco requested changes
Hi @SantiagoGuerra and @lhscar56 :high_brightness: 

Everything looks fine but there are still two points from the previous review left to cover. I left some comments below addressing them.

Regards!

----------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-12-18 23:21 UTC, samgaco commented on app/controllers/sessions_controller.rb
> +    redirect_to signup_path
As said by @Ispirett 

> This method should set the @current_user to nil [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/session_delete_requirement.png)

Please, read the requirement in the odin project in [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/session_delete_requirement.png)

2019-12-18 23:21 UTC, samgaco commented on app/controllers/sessions_controller.rb
> +      cookies.permanent[:remember_token] = user.remember_token
as said by @Ispirett 
> You should be giving the User a new remember token here [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png)
> eg:
> 
> ```
>  remember_token = User.generate_remember_token
>   user.update_attribute(:remember_token, remember_token)
>   cookies.permanent[:remember_token] = remember_token
> ```


You can check the requirement in this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png)

2019-12-20 05:59 UTC, mcrd25 approved these changes
# Project Approved. 🎊 ㊗️ 🎉 🤓 

Hi Team!

We are finally at the finish line 🏁! 👍 

I see no need for further review!

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2019-12-20 05:59 UTC, mcrd25 commented on app/controllers/sessions_controller.rb
> +    cookies.delete :remember_token
[OPTIONAL]
You may even consider setting the user's remember_token in DB to nil for security purposes.

2019-12-20 15:13 UTC, merged